version: '2'
services:
  soundgram-app:
    image: soundgram
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://soundgram-postgresql:5432/Soundgram
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://soundgram-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://soundgram-elasticsearch:9200
    ports:
      - 8080:8080
  soundgram-postgresql:
    extends:
      file: postgresql.yml
      service: soundgram-postgresql
  soundgram-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: soundgram-elasticsearch
